# version: '3'
services:
  web:
    build:
      context: ./setup
      dockerfile: Dockerfile
    image: ghcr.io/cybermouflons/gtbq-2024/baby-flask:latest
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=/app/app.py
      - FLASK_ENV=development
    volumes:
      - ./setup/app/:/app
