version: "3.7"

services:
  challenge:
    restart: always
    ports:
      - 1337:1337
    build:
      context: ./setup
      dockerfile: Dockerfile
      labels: 
        ctf.challenge.name: deprecated-hms
