services:
  challenge:
    restart: always
    ports:
      - 1337:1337
    image: ghcr.io/cybermouflons/gtbq-2024/deprecated-hms:latest
    build:
      context: ./setup
      dockerfile: Dockerfile
      labels: 
        ctf.challenge.name: deprecated-hms
