version: '3'
services:
  web:
    build:
      context: ./setup
      dockerfile: Dockerfile
    image: ghcr.io/cybermouflons/gtbq-2024/biscuits:latest
    ports:
      - 1337:80
    environment:
      - FLAG=GTBQ{c00ki3s_ar3_d3lici0us}
      - FLASK_APP=/app/app.py
      - FLASK_ENV=development
    # volumes:
    #   - ./setup/app:/app
