version: "3.7"

services:
  challenge:
    restart: always
    ports:
      - 1337:1337
    image: ghcr.io/cybermouflons/gtbq-2024/ticket-check:latest
    build:
      context: ./setup
      dockerfile: Dockerfile
      labels: 
        ctf.challenge.name: ticket-check
