version: '3'
services:
  web:
    build:
      context: ./setup
      dockerfile: Dockerfile
    image: ghcr.io/cybermouflons/gtbq-2024/flask-master:latest
    ports:
      - 1337:80
    volumes:
      - ./setup/app:/app
    environment:
      - FLASK_APP=/app/app.py
      - FLASK_ENV=development
